# Database connection
url=jdbc:postgresql://localhost:5432/liquibase_demo
username=postgres
password=postgres
driver=org.postgresql.Driver

# Master changelog
changeLogFile=changelog/db.changelog.xml

datadog.password=MyLocalPassword123!

# Logging
logLevel=INFO